M48
; DRILL file {KiCad 7.0.9} date Friday, December 15, 2023 at 09:36:52 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-15T09:36:52+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.0415Y-0.9763
T2
X2.1003Y-1.5543
X2.1053Y-0.7043
X3.1503Y-0.7193
X3.1503Y-1.5543
T0
M30
