M48
; DRILL file {KiCad (7.0.0-0)} date Friday 03 November 2023 at 17:36:42
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-03T17:36:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.4724
%
G90
G05
T1
X1.3803Y-0.89
X1.3803Y-2.965
X3.9365Y-0.89
X3.9365Y-2.965
T2
X1.7517Y-1.92
X2.6275Y-1.23
X3.484Y-1.92
T0
M30
