M48
; DRILL file {KiCad (7.0.0-0)} date Friday 03 November 2023 at 17:36:42
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-03T17:36:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X2.5291Y-2.8409
X2.6275Y-2.8409
X2.7259Y-2.8409
T2
X1.7517Y-2.6793
X2.6275Y-2.01
X3.484Y-2.6793
T0
M30
