M48
; DRILL file {KiCad 7.0.9} date Sunday, November 12, 2023 at 11:40:14 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-12T11:40:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X1.8106Y-1.2329
X1.8106Y-1.5779
X1.85Y-0.905
X1.85Y-1.85
X3.595Y-0.91
X3.595Y-1.85
T2
X2.455Y-1.005
T0
M30
