M48
; DRILL file {KiCad 7.0.9} date Saturday, November 11, 2023 at 09:59:13 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-11T09:59:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X2.4938Y-1.87
X2.9688Y-0.82
T2
X2.8688Y-1.8759
T0
M30
