M48
; DRILL file {KiCad 7.0.9} date Monday, December 11, 2023 at 03:48:04 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-11T15:48:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X1.705Y-1.095
X3.51Y-1.095
X3.51Y-2.28
T2
X1.8011Y-1.435
X2.7105Y-1.435
T0
M30
