M48
; DRILL file {KiCad (7.0.0-0)} date Monday 06 November 2023 at 21:22:25
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T21:22:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.2699Y-0.9649
X2.2699Y-1.7449
X2.9449Y-0.9649
X2.9449Y-1.7449
T0
M30
