M48
; DRILL file {KiCad 7.0.9} date Monday, December 11, 2023 at 11:26:02 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-11T11:26:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.275Y-0.68
X2.28Y-2.135
X3.305Y-0.68
X3.305Y-2.135
T0
M30
